name: Automatic deploy to dev environment
on:
  push:
    branches:
      - dev
jobs:
  Check:
    runs-on: pop-os
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Cache environment
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check
        run: python manage.py check
  Deploy:
    runs-on: ubuntu-latest
    needs: Check
    steps:
      - name: git pull
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo hihi
